# ============================================================
# reporting/report_templates.py
# PURPOSE: Multiple report templates for incident reporting
#          As suggested in the evaluation report
#
# Templates:
#   1. standard       - Full detailed report (default)
#   2. executive      - Brief business-focused summary
#   3. technical      - Deep technical analysis
# ============================================================

from datetime import datetime, timezone
from typing import Dict


def get_standard_template(rca_report: Dict) -> str:
    """Full SRE incident report — covers all 8 sections."""
    primary = rca_report.get("primary_anomaly", {})
    blast   = rca_report.get("blast_radius", {})
    fixes   = rca_report.get("recommended_fixes", [])
    hypo    = rca_report.get("hypotheses", [])
    similar = rca_report.get("similar_incidents", [])

    return f"""
╔══════════════════════════════════════════════════════════════╗
║           PROJECT 71 — INCIDENT REPORT (STANDARD)           ║
╚══════════════════════════════════════════════════════════════╝

INCIDENT ID   : {rca_report.get('incident_id', 'N/A')}
TIMESTAMP     : {rca_report.get('timestamp', 'N/A')}
SEVERITY      : SEV-{rca_report.get('severity', 4)} — {
    {1:'CRITICAL',2:'HIGH',3:'MEDIUM',4:'LOW'}.get(rca_report.get('severity',4),'UNKNOWN')}
OWNING TEAM   : {rca_report.get('owning_team', 'N/A')}
TEMPLATE      : Standard

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. INCIDENT SUMMARY
   Root Cause Service : {rca_report.get('root_cause_service', 'N/A')}
   Root Cause Summary : {rca_report.get('root_cause_summary', 'N/A')}

2. BUSINESS IMPACT
   Directly Affected  : {', '.join(blast.get('directly_affected', [])) or 'None'}
   Indirectly Affected: {', '.join(blast.get('indirectly_affected', [])) or 'None'}
   Total Services Hit : {blast.get('total_affected', 0)}
   Criticality Score  : {blast.get('criticality_score', 0)}

3. PRIMARY ANOMALY DETECTED
   Type           : {primary.get('type', 'N/A')}
   Metric         : {primary.get('metric_name', 'N/A')}
   Observed Value : {primary.get('observed_value', 'N/A')}
   Expected Value : {primary.get('expected_value', 'N/A')}
   Anomaly Severity: {primary.get('severity', 'N/A')}

4. ROOT CAUSE ANALYSIS
   {rca_report.get('root_cause_summary', 'Analysis pending.')}

5. HYPOTHESES
   {chr(10).join(f'   {i+1}. {h}' for i, h in enumerate(hypo[:3])) or '   No hypotheses generated.'}

6. IMMEDIATE ACTIONS
   {chr(10).join(f'   {i+1}. {f}' for i, f in enumerate(fixes[:3])) or '   No fixes recommended.'}

7. SIMILAR PAST INCIDENTS
   {', '.join(similar) if similar else 'No similar incidents found in knowledge base.'}

8. LESSONS LEARNED
   This incident has been automatically saved to the knowledge
   base to improve future detection and response accuracy.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Project 71 AIOps Platform | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC
""".strip()


def get_executive_template(rca_report: Dict) -> str:
    """Executive summary — brief, business-focused, non-technical."""
    blast   = rca_report.get("blast_radius", {})
    fixes   = rca_report.get("recommended_fixes", [])
    sev_map = {1:'CRITICAL',2:'HIGH',3:'MEDIUM',4:'LOW'}
    sev     = sev_map.get(rca_report.get('severity', 4), 'UNKNOWN')

    return f"""
╔══════════════════════════════════════════════════════════════╗
║         PROJECT 71 — INCIDENT REPORT (EXECUTIVE)            ║
╚══════════════════════════════════════════════════════════════╝

INCIDENT  : {rca_report.get('incident_id', 'N/A')}
SEVERITY  : SEV-{rca_report.get('severity', 4)} ({sev})
TIME      : {rca_report.get('timestamp', 'N/A')}
TEAM      : {rca_report.get('owning_team', 'N/A')}
TEMPLATE  : Executive Summary

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WHAT HAPPENED
  {rca_report.get('root_cause_summary', 'N/A')}

BUSINESS IMPACT
  {blast.get('total_affected', 0)} service(s) affected.
  Directly: {', '.join(blast.get('directly_affected', [])) or 'None'}

TOP RECOMMENDED ACTION
  {fixes[0] if fixes else 'Under investigation.'}

STATUS
  Incident captured and saved to the knowledge base.
  Full technical analysis available in the standard report.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Project 71 AIOps Platform | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC
""".strip()


def get_technical_template(rca_report: Dict) -> str:
    """Technical deep-dive — for SRE and engineering teams."""
    primary = rca_report.get("primary_anomaly", {})
    blast   = rca_report.get("blast_radius", {})
    fixes   = rca_report.get("recommended_fixes", [])
    hypo    = rca_report.get("hypotheses", [])
    similar = rca_report.get("similar_incidents", [])

    return f"""
╔══════════════════════════════════════════════════════════════╗
║         PROJECT 71 — INCIDENT REPORT (TECHNICAL)            ║
╚══════════════════════════════════════════════════════════════╝

INCIDENT ID     : {rca_report.get('incident_id', 'N/A')}
TIMESTAMP       : {rca_report.get('timestamp', 'N/A')}
SEVERITY LEVEL  : SEV-{rca_report.get('severity', 4)}
OWNING TEAM     : {rca_report.get('owning_team', 'N/A')}
TEMPLATE        : Technical Deep Dive

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[ANOMALY DETECTION]
  Root Cause Service : {rca_report.get('root_cause_service', 'N/A')}
  Anomaly Type       : {primary.get('type', 'N/A')}
  Metric             : {primary.get('metric_name', 'N/A')}
  Observed Value     : {primary.get('observed_value', 'N/A')}
  Expected Value     : {primary.get('expected_value', 'N/A')}
  Detection Severity : {primary.get('severity', 'N/A')} / 4
  Description        : {primary.get('description', 'N/A')}

[DEPENDENCY GRAPH ANALYSIS]
  Root Service       : {rca_report.get('root_cause_service', 'N/A')}
  Directly Affected  : {', '.join(blast.get('directly_affected', [])) or 'None'}
  Indirectly Affected: {', '.join(blast.get('indirectly_affected', [])) or 'None'}
  Total Affected     : {blast.get('total_affected', 0)}
  Criticality Score  : {blast.get('criticality_score', 0)}

[RAG RETRIEVAL]
  Similar Incidents  : {', '.join(similar) if similar else 'None found'}
  Knowledge Base     : Auto-learning enabled

[HYPOTHESES — RANKED BY PROBABILITY]
{chr(10).join(f'  {i+1}. {h}' for i, h in enumerate(hypo)) or '  None generated.'}

[RECOMMENDED FIXES — PRIORITIZED]
{chr(10).join(f'  {i+1}. {f}' for i, f in enumerate(fixes)) or '  None recommended.'}

[ROOT CAUSE SUMMARY]
  {rca_report.get('root_cause_summary', 'N/A')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Project 71 AIOps Platform | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC
""".strip()


TEMPLATES = {
    "standard":  get_standard_template,
    "executive": get_executive_template,
    "technical": get_technical_template,
}


def generate_report(rca_report: Dict,
                    template: str = "standard") -> str:
    """
    Generates an incident report using the specified template.

    Args:
        rca_report: Structured RCA report dict
        template:   'standard' | 'executive' | 'technical'

    Returns:
        Formatted report string
    """
    generator = TEMPLATES.get(template, get_standard_template)
    return generator(rca_report)
